<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Agents.AI" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\ConsoleReactiveFramework\ConsoleReactiveFramework.csproj" />
		<ProjectReference Include="..\ConsoleReactiveComponents\ConsoleReactiveComponents.csproj" />
	</ItemGroup>

</Project>
